# Generated by Django 2.2.3 on 2019-08-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_post',
            old_name='status',
            new_name='publish',
        ),
    ]
