# Generated by Django 2.2.3 on 2019-08-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190824_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_post',
            options={'ordering': ['-created_at', '-updated']},
        ),
    ]
