# Generated by Django 2.0.8 on 2019-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190824_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_post',
            name='sub_category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
